import React, { useState, useEffect } from 'react';
import api from '../services/api';
import ReportCard from '../components/daily-report/ReportCard';
import ReasonModal from '../components/daily-report/ReasonModal';

const DailyReportPage = () => {
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [selectedSignal, setSelectedSignal] = useState(null);

    useEffect(() => {
        fetchReport();
    }, []);

    const fetchReport = async () => {
        setLoading(true);
        setError('');
        try {
            const response = await api.get('/api/daily-report');
            setReport(response.data);
        } catch (err) {
            console.error(err);
            setError('Failed to fetch the daily market report. Please ensure your Groq API key is set.');
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <div style={styles.centerContainer}>
                <div className="spinner"></div>
                <p style={{ marginTop: '16px', color: '#94a3b8' }}>Generating AI Market Insights...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div style={styles.centerContainer}>
                <div className="error-message" style={{ maxWidth: '400px', textAlign: 'center' }}>
                    {error}
                </div>
                <button onClick={fetchReport} style={styles.retryBtn}>Retry</button>
                <a href="/dashboard" style={styles.backLink}>Back to Dashboard</a>
            </div>
        );
    }

    return (
        <div style={styles.page}>
            <header style={styles.header}>
                <div>
                    <h1 style={styles.title}>AI Daily Market Report</h1>
                    <p style={styles.subtitle}>
                        {report?.date ? new Date(report.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : 'Today'}
                    </p>
                </div>
                <a href="/dashboard" style={styles.dashboardBtn}>Dashboard</a>
            </header>

            <div style={styles.content}>
                {/* Positive Signals Section */}
                <section style={styles.section}>
                    <div style={styles.sectionHeader}>
                        <div style={styles.indicator} className="positive"></div>
                        <h2 style={styles.sectionTitle}>Opportunity Watchlist</h2>
                    </div>
                    <div style={styles.grid}>
                        {report?.positiveSignals?.map((signal, idx) => (
                            <ReportCard
                                key={`pos-${idx}`}
                                signal={signal}
                                type="positive"
                                onShowReason={setSelectedSignal}
                            />
                        ))}
                    </div>
                    {(!report?.positiveSignals || report.positiveSignals.length === 0) && (
                        <p style={styles.emptyText}>No positive signals detected for today.</p>
                    )}
                </section>

                {/* Negative Signals Section */}
                <section style={styles.section}>
                    <div style={styles.sectionHeader}>
                        <div style={styles.indicator} className="negative"></div>
                        <h2 style={styles.sectionTitle}>Risk Alerts</h2>
                    </div>
                    <div style={styles.grid}>
                        {report?.negativeSignals?.map((signal, idx) => (
                            <ReportCard
                                key={`neg-${idx}`}
                                signal={signal}
                                type="negative"
                                onShowReason={setSelectedSignal}
                            />
                        ))}
                    </div>
                    {(!report?.negativeSignals || report.negativeSignals.length === 0) && (
                        <p style={styles.emptyText}>No major risks detected in your portfolio sectors.</p>
                    )}
                </section>
            </div>

            <footer style={styles.footer}>
                <p>Generated by VisAlpha AI • Data from NewsAPI & Market Services</p>
            </footer>

            <ReasonModal
                isOpen={!!selectedSignal}
                onClose={() => setSelectedSignal(null)}
                data={selectedSignal}
            />
        </div>
    );
};

const styles = {
    page: {
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '32px 24px',
        minHeight: '100vh',
        backgroundColor: '#020617',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '40px',
        borderBottom: '1px solid #1e293b',
        paddingBottom: '24px',
    },
    title: {
        fontSize: '32px',
        fontWeight: '800',
        color: '#f8fafc',
        margin: 0,
        background: 'linear-gradient(to right, #3b82f6, #60a5fa)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
    },
    subtitle: {
        color: '#64748b',
        marginTop: '8px',
        fontSize: '16px',
    },
    dashboardBtn: {
        backgroundColor: '#1e293b',
        color: 'white',
        textDecoration: 'none',
        padding: '10px 20px',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '600',
        transition: 'all 0.2s',
        border: '1px solid #334155',
    },
    content: {
        display: 'flex',
        flexDirection: 'column',
        gap: '48px',
    },
    section: {
        animation: 'fadeIn 0.5s ease-out',
    },
    sectionHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '24px',
    },
    indicator: {
        width: '12px',
        height: '12px',
        borderRadius: '3px',
        '&.positive': {
            backgroundColor: '#22c55e',
            boxShadow: '0 0 10px rgba(34, 197, 94, 0.4)',
        },
        '&.negative': {
            backgroundColor: '#ef4444',
            boxShadow: '0 0 10px rgba(239, 68, 68, 0.4)',
        }
    },
    sectionTitle: {
        fontSize: '20px',
        fontWeight: '700',
        color: '#f1f5f9',
        margin: 0,
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
        gap: '24px',
    },
    emptyText: {
        color: '#475569',
        fontStyle: 'italic',
        marginTop: '12px',
    },
    centerContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '80vh',
    },
    retryBtn: {
        backgroundColor: '#3b82f6',
        color: 'white',
        border: 'none',
        padding: '10px 24px',
        borderRadius: '8px',
        marginTop: '20px',
        cursor: 'pointer',
    },
    backLink: {
        color: '#64748b',
        marginTop: '16px',
        textDecoration: 'none',
        fontSize: '14px',
    },
    footer: {
        marginTop: '64px',
        paddingTop: '24px',
        borderTop: '1px solid #1e293b',
        textAlign: 'center',
        color: '#475569',
        fontSize: '12px',
    }
};

export default DailyReportPage;
