import React, { useState, useEffect } from 'react';

const DisclaimerModal = ({ pageName }) => {
    const [isOpen, setIsOpen] = useState(false);

    useEffect(() => {
        // Check if the user has already accepted the disclaimer for this specific page within the last 7 days
        const storageKey = `visalpha_disclaimer_${pageName.replace(/\s+/g, '_').toLowerCase()}_accepted_date`;
        const acceptedDateStr = localStorage.getItem(storageKey);
        
        if (!acceptedDateStr) {
            setIsOpen(true);
        } else {
            const acceptedDate = parseInt(acceptedDateStr, 10);
            const now = new Date().getTime();
            const oneWeekInMs = 7 * 24 * 60 * 60 * 1000;
            
            // If it has been more than a week, show the disclaimer again
            if (now - acceptedDate > oneWeekInMs) {
                setIsOpen(true);
            }
        }
    }, [pageName]);

    const handleAccept = () => {
        const storageKey = `visalpha_disclaimer_${pageName.replace(/\s+/g, '_').toLowerCase()}_accepted_date`;
        localStorage.setItem(storageKey, new Date().getTime().toString());
        setIsOpen(false);
    };

    if (!isOpen) return null;

    return (
        <div style={styles.overlay}>
            <div style={styles.modal}>
                <div style={styles.header}>
                    <h2 style={styles.title}>⚠️ Important Disclaimer</h2>
                </div>
                <div style={styles.body}>
                    <p style={styles.text}>
                        The information provided on the <strong>{pageName}</strong> is generated by artificial intelligence and is strictly for informational and educational purposes only. It does not constitute professional financial, investment, legal, or tax advice.
                    </p>
                    <p style={styles.text}>
                        Trading stocks, options, and other financial instruments involves a significant risk of loss and is not suitable for every investor. The AI analysis may contain errors, inaccuracies, or rely on delayed data.
                    </p>
                    <p style={styles.text}>
                        Always conduct your own due diligence and consult with a certified financial advisor or professional broker before making any investment decisions. VisAlpha Capital and its affiliates bear no responsibility for any financial losses incurred based on this information.
                    </p>
                </div>
                <div style={styles.footer}>
                    <button style={styles.acceptBtn} onClick={handleAccept} className="accept-btn">
                        I Understand and Accept
                    </button>
                </div>
            </div>
            <style>{`
                @keyframes modalFadeIn {
                    from { opacity: 0; transform: translateY(-20px) scale(0.95); }
                    to { opacity: 1; transform: translateY(0) scale(1); }
                }
                .accept-btn:hover {
                    background-color: #1d4ed8 !important; /* blue-700 */
                }
            `}</style>
        </div>
    );
};

const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999,
        backdropFilter: 'blur(5px)',
    },
    modal: {
        backgroundColor: '#1e293b',
        borderRadius: '12px',
        width: '90%',
        maxWidth: '550px',
        padding: '32px',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
        border: '1px solid #334155',
        animation: 'modalFadeIn 0.3s ease-out',
        color: '#f8fafc',
    },
    header: {
        marginBottom: '20px',
        borderBottom: '1px solid #334155',
        paddingBottom: '16px',
    },
    title: {
        margin: 0,
        fontSize: '22px',
        fontWeight: '700',
        color: '#eab308',
    },
    body: {
        marginBottom: '24px',
    },
    text: {
        fontSize: '15px',
        lineHeight: '1.6',
        color: '#cbd5e1',
        marginBottom: '16px',
    },
    footer: {
        display: 'flex',
        justifyContent: 'flex-end',
        borderTop: '1px solid #334155',
        paddingTop: '20px',
    },
    acceptBtn: {
        backgroundColor: '#2563eb',
        color: 'white',
        border: 'none',
        padding: '12px 24px',
        borderRadius: '8px',
        fontWeight: '600',
        fontSize: '15px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
        boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    }
};

export default DisclaimerModal;
